### ISSUE TITLE
Mycroft GUI Mark-2 Repository Documentation

### ISSUE THREAD

**Issue by AIIX** [MycroftAI/mycroft-gui-mark-2#14]
#### General Pull Down Menu:
This is where you can find the button implementation for the pull down menu 
- https://github.com/MycroftAI/mycroft-gui-mark-2/tree/master/containments/mark2/package/contents/ui/panel/contents/ui/quicksettings
- https://github.com/MycroftAI/mycroft-gui-mark-2/blob/master/containments/mark2/package/contents/ui/panel/contents/ui/quicksettings/QuickSettings.qml

#### Volume Slider in Pull Down Menu:
This is where you can find the volume slider implementation for the pull down menu
- https://github.com/MycroftAI/mycroft-gui-mark-2/blob/master/containments/mark2/package/contents/ui/panel/contents/ui/quicksettings/VolumeSlider.qml

#### Volume Slider on Main Screen:
This is where you can find the volume slider implementation for the main screen
- https://github.com/MycroftAI/mycroft-gui-mark-2/blob/master/containments/mark2/package/contents/ui/VolumeFeedbackGraphics.qml

#### Virtual Keyboard:
This is where you can find the virtual keyboard implementation 
- https://github.com/MycroftAI/mycroft-gui-mark-2/blob/master/containments/mark2/package/contents/ui/VirtualKeyboardLoader.qml
- https://github.com/MycroftAI/mycroft-gui-mark-2/blob/master/containments/mark2/package/contents/ui/VirtualKeyboard.qml

#### On Device Networking:
This is where you can find the Plasma network manager implementation
- https://github.com/MycroftAI/mycroft-gui-mark-2/blob/master/containments/mark2/package/contents/ui/NetworkingLoader.qml
- https://github.com/MycroftAI/mycroft-gui-mark-2/tree/master/containments/mark2/package/contents/ui/networking

#### Shutdown, Reboot Button Implementation:
This is where you can find the implementation for action that takes place when shutdown is clicked
- https://github.com/MycroftAI/mycroft-gui-mark-2/blob/master/containments/mark2/plugin/mark2systemaccess.cpp

#### Splash Screen:
First animation played when containment starts up
- https://github.com/MycroftAI/mycroft-gui-mark-2/tree/master/lookandfeel/contents/splash

#### Screen Rotation
Configuration for screen rotation
- https://github.com/MycroftAI/mycroft-gui-mark-2/blob/master/lookandfeel/contents/plasmoidsetupscripts/org.kde.mycroft.mark2.js

**Comment by krisgesling** [comment]
This is excellent, thanks so much!

**Comment by krisgesling** [comment]
I thought about putting it in our main docs, but given this is very explicitly about the code I added it to this repo's wiki instead.
