### ISSUE TITLE
Video playback not working

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/mycroft-gui-mark-2#18]
Video playback does not seem to be working on the Mark II and Ubuntu 20.04, returns a black screen. 

Using the following mycroft-core PR:
https://github.com/MycroftAI/mycroft-core/pull/2683

And a simple demo Skill:
https://github.com/krisgesling/play-a-video-skill/

Possibilities:
- only some video types are supported and the current videos being used are not - need to define any limitations of the system here
- QML not rendering correctly
- ?

**Comment by AIIX** [comment]
Should be fixed in https://github.com/MycroftAI/mycroft-core/pull/2683 also requires https://github.com/MycroftAI/skill-mark-2/pull/57

**Comment by krisgesling** [comment]
Excellent, thanks!
