### ISSUE TITLE
Update Menu design

### ISSUE THREAD

**Issue by dschweppe** [MycroftAI/mycroft-gui-mark-2#20]
Update menu design based on these mockups:
https://www.figma.com/file/eQGAYPY0cTKvmU8OJ113Sv/Mark-II-GUI-Production?node-id=1801%3A45

![Menu](https://user-images.githubusercontent.com/24575886/108066858-915faf00-7025-11eb-912c-694782a08d5b.png)

**Comment by krisgesling** [comment]
All merged and looking great :)
