### ISSUE TITLE
Get Camera Working on Pantacor Image

### ISSUE THREAD

**Issue by AIIX** [MycroftAI/mycroft-gui-mark-2#23]
Camera does not work with the image without the following configuration.

To Get Camera Working on Pantacor Image:

1. Install & build https://github.com/raspberrypi/userland under Mycroft Container
    - git clone https://github.com/raspberrypi/userland
    - cd userland
    - ./buildme --arch64

2. Edit boot partition config.txt add: 
    - start_x=1 (under [ALL])
    
3. Add mycroft user to video group: 
    - sudo usermod -a -G video mycroft
    
4. Fix /dev/vchiq group and permissions:
    - sudo chgrp video /dev/vchiq
    - sudo chmod 0660  /dev/vchiq
    
5. Add /opt/vc/lib to LD_LIBRARY_PATH:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/vc/lib/

**Comment by AIIX** [comment]
Can be tested with an updated camera skill: https://github.com/AIIX/skill-camera

**Comment by krisgesling** [comment]
This is in the latest Pantacor image now
