### ISSUE TITLE
Timer Skill text resizing problem

### ISSUE THREAD

**Issue by dschweppe** [MycroftAI/mycroft-gui-mark-2#25]
Steps to reproduce:
Set 4 timers (2 minutes, 5 minutes, 7 minutes, 9 minutes, duration isn't really important)
Delete 9 minute timer (hey mycroft delete the 9 minute timer)
Delete 7 minute timer (hey mycroft delete the 7 minute timer)

When the timer GUI returns to two active timers the text will be the incorrect size.

![image](https://user-images.githubusercontent.com/24575886/111241571-6e480100-85cb-11eb-9a2f-8dbac7e5ed68.png)

**Comment by AIIX** [comment]
is this running the latest mycroft-timer skill with the text size fixes ? https://github.com/MycroftAI/mycroft-timer/pull/88

**Comment by krisgesling** [comment]
This is definitely addressed already
